name: SusSMP
version: 1.4.2
main: id.kuru.sussmp.SusPlugin
api-version: '1.21'
description: Social deduction ala Among Us - 10 player, 4 bos task, meeting bell, vote chat
commands:
  sus:
    description: Perintah utama SusSMP
    usage: /sus <add|remove|start|stop|meetingtime|cooldown|impostors|setlobby|setroom>
  vote:
    description: Buka GUI voting (hanya saat meeting)
    usage: /vote
permissions:
  sus.admin:
    description: Kelola game SusSMP
    default: op
